Repository Gschaftlhaberer/gschaeftlhaberer, pull requests merged in 2024-03, with the labels that each got.

#22 chore: move SvelteKit app after multiple explicit requests from the customer
  .github/.dockerignore
  .github/workflows/main-publish.yml
  .github/workflows/main-technical-document.yml
  .github/workflows/release-publish.yml
  .github/workflows/test.yml
  .vscode/.dockerignore
  app/.eslintignore
  app/.eslintrc.cjs
  app/.gitignore
  app/.npmrc
  app/.prettierignore
  app/.prettierrc
  app/docker-compose.yaml
  app/package.json
  app/playwright.config.ts
  app/pnpm-lock.yaml
  app/postcss.config.cjs
  app/src/app.d.ts
  app/src/app.html
  app/src/app.pcss
  app/src/index.test.ts
  app/src/lib/components/GlobalNav.svelte
  app/src/lib/db.ts
  app/src/lib/index.ts
  app/src/routes/+layout.svelte
  app/src/routes/+layout.ts
  app/src/routes/+page.svelte
  app/src/routes/settings/+page.svelte
  app/static/favicon.png
  app/svelte.config.js
  app/tailwind.config.cjs
  app/tests/test.ts
  app/tsconfig.json
  app/vite.config.ts
  technical-document/.dockerignore
Labels: chore

#25 docs: add sources to technical document
  technical-document/_solution.tex
  technical-document/_task.tex
  technical-document/bibliography.bib
Labels: docs

#27 Feat/show product lists
  app/package.json
  app/pnpm-lock.yaml
  app/src/lib/components/ProductList.svelte
  app/src/lib/db.ts
  app/src/routes/+layout.svelte
  app/src/routes/+page.svelte
  app/src/routes/+page.ts
  app/tests/lists.test.ts
  app/tests/test.ts
Labels: feat

#30 Feat/create offline service
  app/src/service-worker.ts
Labels: feat
